modLoader="javafml"
loaderVersion="[2,)"
license="GNU GPL v3"

[[mixins]]
config="rocketnautics.mixins.json"
[[mixins]]
config="dimensional_sable.mixins.json"

[[mods]]
modId="rocketnautics"
version="${file.jarVersion}"
displayName="Create: Cosmonautics"
displayURL="https://github.com/CosmonauticsTeam/Create-Cosmonautics"
authors="webyep-art, M_W_K"
description='''
Space addon for Create Aeronautics!
'''

[[mods]]
modId="dimensional_sable"
version="1.0.5"
displayName="Dimensional Sable"
description='''Dimensional Support for Sable'''

[[dependencies.rocketnautics]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.rocketnautics]]
modId="neoforge"
type="required"
versionRange="[21.1.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.rocketnautics]]
modId="create"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.rocketnautics]]
modId="aeronautics"
type="required"
versionRange="[1.0.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.rocketnautics]]
modId="dimensional_sable"
type="required"
versionRange="[1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.dimensional_sable]]
modId="neoforge"
type="required"
versionRange="[21.1.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.dimensional_sable]]
modId="sable"
type="required"
versionRange="[2.0.3,)"
ordering="NONE"
side="BOTH"

[mc-publish]
dependencies=[
  "aeronautics(required){modrinth:create-aeronautics}{curseforge:create-aeronautics}"
]
